### ISSUE TITLE
Error (Xcode): could not compile `proc-macro-error` due to 6 previous errors

### ISSUE THREAD

**Issue by ws-97** [superlistapp/super_native_extensions#120]
i can run the demo on mac device ,
but when run on IOS ,it report this problem
![image](https://user-images.githubusercontent.com/65961541/236617631-937bd372-ac9d-4093-aa28-1f23686db4b8.png)

**Comment by knopp** [comment]
Can you post the entire log?

**Comment by ws-97** [comment]
i am sorry for that, this is the entire log.
i run this demo on intellj IDEA









[   +3 ms] Failed to build iOS app

[        ] Error (Xcode): could not compile `proc-macro-error` due to 6 previous errors




[   +1 ms] Could not build the application for the simulator.

[        ] Error launching application on iPhone 12 mini.

[   +1 ms] 

           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)

           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:624:9)

           <asynchronous suspension>

           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)

           <asynchronous suspension>

           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)

           <asynchronous suspension>

           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)

           <asynchronous suspension>

           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)

           <asynchronous suspension>

           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)

           <asynchronous suspension>

           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #10     main (package:flutter_tools/executable.dart:91:3)

           <asynchronous suspension>







[{"event":"app.stop","params":{"appId":"3587946f-e31a-4ba6-b39e-a61abff255d6"}}]

[   +1 ms] "flutter run" took 19,482ms.

[{"id":0,"error":"app '3587946f-e31a-4ba6-b39e-a61abff255d6' not found","trace":"#0      AppDomain.stop (package:flutter_tools/src/commands/daemon.dart:769:7)\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:274:35)\n#2      new Future.sync (dart:async/future.dart:302:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:272:5)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:224:27)\n#5      _rootRunUnary (dart:async/zone.dart:1406:47)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#9      _DelayedData.perform (dart:async/stream_impl.dart:515:14)\n#10     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)\n#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)\n#12     _rootRun (dart:async/zone.dart:1390:47)\n#13     _CustomZone.run (dart:async/zone.dart:1300:19)\n#14     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)\n#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)\n#16     _rootRun (dart:async/zone.dart:1398:13)\n#17     _CustomZone.run (dart:async/zone.dart:1300:19)\n#18     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)\n#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)\n#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)\n#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)\n#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)\n#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)\n"}]













----- Original Message -----

**Comment by knopp** [comment]
That doesn't show the root issue. Can you run it from command line with the verbose (-v) flag? i..e.
``` 
flutter run -v -d <device_id>
```

**Comment by knopp** [comment]
I'm closing this for inactivity. Please reopen if the issue persist and you can provide the verbose log.
