### ISSUE TITLE
[Question] how to use this extension ?

### ISSUE THREAD

**Issue by nesteiner** [superlistapp/super_native_extensions#219]
hey, I have follow the README
1. download the repository to the root of project
2. flutter pub add melos
3. add melos.yaml
4. run `melos bootstrap`
5. flutter run -t lib/testui/testui.dart

this is my `melos.yaml`
```yaml
name: filemanager

packages:
  - "*"
  - super_native_extensions/**
 
```

and this is part of `lib/testui/testui.dart`
```dart
import 'package:flutter/material.dart';
import 'package:super_clipboard/super_clipboard.dart';
```

when running `flutter run -t lib/testui/testui.dart`
the error is 
```
aunching lib/testui/testui.dart on Linux in debug mode...
Building Linux application...
ERROR: Invalid depfile: /home/steiner/workspace/flutter-scratch/filemanager/.dart_tool/flutter_build/705fe01a2b73c17a1fc49c7bb79a3548/kernel_snapshot.d
ERROR: Invalid depfile: /home/steiner/workspace/flutter-scratch/filemanager/.dart_tool/flutter_build/705fe01a2b73c17a1fc49c7bb79a3548/kernel_snapshot.d
ERROR: Error: Couldn't resolve the package 'super_clipboard' in 'package:super_clipboard/super_clipboard.dart'.
ERROR: lib/testui/testui.dart:2:8: Error: Not found: 'package:super_clipboard/super_clipboard.dart'
ERROR: import 'package:super_clipboard/super_clipboard.dart';
```

and this is my project
![image](https://github.com/superlistapp/super_native_extensions/assets/46296608/adc624dd-8c0b-4c1e-9027-e4b4fc6d80a5)

**Comment by knopp** [comment]
Why did you download the repository to your project? You should use it like any other pub package / plugin, declare it as dependency in pubspec.yaml.

**Comment by nesteiner** [comment]
ok, reset the project
1. delete the super_native_extensions
2. edit `melos.yaml`
3. `flutter pub add super_clipboard`
4. `melos bootstrap`
5. `flutter run -t lib/testui/testui.dart -v`

this is the `melos.yaml`
```yaml
name: filemanager

packages:
  - "*"
```

this is the result of step 5
```
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Comment by knopp** [comment]
If you just want to use super_drag_and_drop in the project:

```
flutter create my_project
cd my_project
flutter pub add super_clipboard
flutter run -t lib/main.dart -v
```

This should just work, like any other flutter package. I'm not entirely sure what your project structure is or why you're even trying to use melos in this case.

**Comment by nesteiner** [comment]
are you sure you can run this code on your machine ?
I have tried
```
flutter create my_project
cd my_project
flutter pub add super_clipboard
flutter run -v
```

I found it is the same error, I think it's the matter of `super_clipboard`, when remove it everything is ok

**Comment by knopp** [comment]
Can you post here the whole log? The actual error is likely somewhere above. Also, which linux distribution do you have? And  how did you install Flutter? By snap or downloaded manually?

**Comment by knopp** [comment]
From the log:
```
/usr/bin/perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```
Are you sure that you have perl working correctly in your distribution?

**Comment by nesteiner** [comment]
oh, shit, when reinstall the perl, everything works well.
it is my fault, sorry to bother you guys :slightly_smiling_face:
