### ISSUE TITLE
Linux arm64 build regression

### ISSUE THREAD

**Issue by adil192** [superlistapp/super_native_extensions#223]
When building for arm64 I get this error which doesn't occur with the x86_64 build:
`SEVERE: error: could not create temp file /opt/rustup/tmp/z3zpim_ym048rjmx_file: Permission denied (os error 13)`

This occured on both 0.7.2 and 0.7.0 but didn't on my last release which used 0.6.4 of super_clipboard.

Also please fill in `CHANGELOG.md` because https://pub.dev/packages/super_clipboard/changelog has lots of blank changelogs

## Longer logs

```
  [+74402 ms] [1/28] Generating libsuper_native_extensions.so, _phony_
  [ +216 ms] FAILED: plugins/super_native_extensions/libsuper_native_extensions.so plugins/super_native_extensions/_phony_ /home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions/libsuper_native_extensions.so /home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions/_phony_ 
  [  +32 ms] cd /home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions && /usr/bin/cmake -E env CARGOKIT_CMAKE=/usr/bin/cmake CARGOKIT_CONFIGURATION=Release CARGOKIT_MANIFEST_DIR=/home/runner/work/saber/saber/linux/flutter/ephemeral/.plugin_symlinks/super_native_extensions/linux/../rust CARGOKIT_TARGET_TEMP_DIR=/home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions/cargokit_build CARGOKIT_OUTPUT_DIR=/home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions CARGOKIT_TARGET_PLATFORM=linux-arm64 CARGOKIT_TOOL_TEMP_DIR=/home/runner/work/saber/saber/build/linux/arm64/release/plugins/super_native_extensions/cargokit_build/tool CARGOKIT_ROOT_PROJECT_DIR=/home/runner/work/saber/saber/linux /home/nonroot/.pub-cache/hosted/pub.dev/super_native_extensions-0.7.0/cargokit/run_build_tool.sh build-cmake
  [   +1 ms] Resolving dependencies...
  [   +3 ms] + adaptive_number 1.0.0
  [   +1 ms] + args 2.4.2
  [   +1 ms] + async 2.11.0
  [   +3 ms] + build_tool 1.0.0 from path /home/nonroot/.pub-cache/hosted/pub.dev/super_native_extensions-0.7.0/cargokit/build_tool
  [        ] + collection 1.18.0
  [   +4 ms] + convert 3.1.1
  [   +1 ms] + crypto 3.0.3
  [        ] + ed25519_edwards 0.3.1
  [   +8 ms] + fixnum 1.1.0
  [   +1 ms] + github 9.17.0 (9.19.0 available)
  [   +1 ms] + hex 0.2.0
  [   +1 ms] + http 1.1.0
  [   +1 ms] + http_parser 4.0.2
  [   +1 ms] + json_annotation 4.8.1
  [        ] + logging 1.2.0
  [        ] + meta 1.11.0
  [        ] + path 1.8.0 (1.8.3 available)
  [   +2 ms] + petitparser 5.4.0 (6.0.1 available)
  [        ] + source_span 1.10.0
  [   +4 ms] + string_scanner 1.2.0
  [        ] + term_glyph 1.2.1
  [        ] + toml 0.14.0
  [        ] + typed_data 1.3.2
  [        ] + version 3.0.0 (3.0.2 available)
  [  +10 ms] + yaml 3.1.2
  [   +1 ms] Changed 25 dependencies!
  [   +1 ms] Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
  [   +1 ms] INFO: Precompiled binaries are disabled
  [   +1 ms] INFO: Installing Rust toolchain: nightly
  [   +1 ms] SEVERE: ================================================================================
  [   +1 ms] SEVERE: Cargokit BuildTool failed with error:
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: External Command: rustup "toolchain" "install" "nightly"
  [  +10 ms] SEVERE: Returned Exit Code: 1
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: STDOUT:
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: STDERR:
  [   +1 ms] SEVERE: info: syncing channel updates for 'nightly-aarch64-unknown-linux-gnu'
  [   +7 ms] SEVERE: error: could not create temp file /opt/rustup/tmp/z3zpim_ym048rjmx_file: Permission denied (os error 13)
  [  +59 ms] SEVERE: --------------------------------------------------------------------------------
  [   +2 ms] SEVERE: #0      runCommand (package:build_tool/src/util.dart:62:5)
  [   +3 ms] SEVERE: #1      Rustup.installToolchain (package:build_tool/src/rustup.dart:26:5)
  [   +2 ms] SEVERE: #2      RustBuilder.prepare (package:build_tool/src/builder.dart:120:14)
  [   +1 ms] SEVERE: #3      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:66:15)
  [        ] SEVERE: <asynchronous suspension>
  [   +1 ms] SEVERE: #4      BuildCMake.build (package:build_tool/src/build_cmake.dart:26:23)
  [  +11 ms] SEVERE: <asynchronous suspension>
  [   +1 ms] SEVERE: #5      BuildCMakeCommand.runBuildCommand (package:build_tool/src/build_tool.dart:76:5)
  [        ] SEVERE: <asynchronous suspension>
  [   +1 ms] SEVERE: #6      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
  [        ] SEVERE: <asynchronous suspension>
  [   +3 ms] SEVERE: #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
  [   +1 ms] SEVERE: <asynchronous suspension>
  [   +2 ms] SEVERE: #8      runMain (package:build_tool/src/build_tool.dart:248:5)
  [        ] SEVERE: <asynchronous suspension>
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [        ] SEVERE: BuildTool arguments: [build-cmake]
  [   +1 ms] SEVERE: ================================================================================
```

## Full logs
https://github.com/saber-notes/saber/actions/runs/6679075874/job/18151123704

**Comment by adil192** [comment]
Nevermind, downgrading to 0.6.4 yields the same error

**Comment by knopp** [comment]
This seems like a permission issue:

```
Cargokit BuildTool failed with error:
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: External Command: rustup "toolchain" "install" "nightly"
  [  +10 ms] SEVERE: Returned Exit Code: 1
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: STDOUT:
  [   +1 ms] SEVERE: --------------------------------------------------------------------------------
  [   +1 ms] SEVERE: STDERR:
  [   +1 ms] SEVERE: info: syncing channel updates for 'nightly-aarch64-unknown-linux-gnu'
  [   +7 ms] SEVERE: error: could not create temp file /opt/rustup/tmp/z3zpim_ym048rjmx_file: Permission denied (os error 13)
```
I'm not sure why your rustup is in opt, but if it is it should be able to write in the directory. The whole point of rustup is to be able to manage rust installations without needing root permissions.

**Comment by adil192** [comment]
Sorry for forgetting about this issue, it looks like it resolved itself and arm64 builds succeed now.
