### ISSUE TITLE
[super_clipboard] Got `Operation not permitted` error on macOS if use the fileUrl from clipboard to read bytes

### ISSUE THREAD

**Issue by boyan01** [superlistapp/super_native_extensions#270]
Thanks for the library.

After upgrading `super_clipboard` from 0.7.3 to 0.8.0, on macOS, when using paste file uri from `~/Download`, the following error occurs. This may be related to permissions, but this problem does not occur in version 0.7.3.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot open file, path = '/Users/user_name/Downloads/log_327.zip' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
#3      MyApp.build.<anonymous closure> (package:my_app/main.dart:38:31)
<asynchronous suspension>
```

exmaple code:

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:super_clipboard/super_clipboard.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: TextButton(
            child: const Text('Paste'),
            onPressed: () async {
              final reader = await ClipboardReader.readClipboard();
              var uris = await Future.wait(
                reader.items
                    .where((element) => element.canProvide(Formats.fileUri))
                    .map((e) => e.readValue(Formats.fileUri))
                    .toList(),
              );
              final files = uris.where((e) => e != null).cast<Uri>();
              if (files.isEmpty) {
                return;
              }
              for (final file in files) {
                final bytes = await File.fromUri(file).readAsBytes();
                debugPrint('uri: $file ${bytes.length}');
              }
            },
          ),
        ),
      ),
    );
  }
}
```

system version:

```
 macOS 14.2 23C64
 darwin-arm64
```

**Comment by knopp** [comment]
This seems related to app sandbox (I assume the application is running sandboxed?). But I'm not aware of anything after 0.7.3 that would cause this.

**Comment by knopp** [comment]
Well, I guess I'm wrong. I did indeed regress.

**Comment by Maksimka101** [comment]
Hello

I have the same exception when read image copied from the telegram app on macos. I use the `super_clipboard` package from the master branch

```
PathAccessException: Cannot open file, path = '/Users/max/Library/Group Containers/6N38VWS5BX.ru.keepcoder.Telegram/appstore/account-16138895038816363150/postbox/media/telegram-cloud-photo-size-2-5402088296315737174-y.jpg' (OS Error: Operation not permitted, errno = 1)
```

Also, I've noticed this error right before the previous one:
```
Error in root zone Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _readAll.<anonymous closure> (package:super_clipboard/src/reader_value.dart:13:15)
#2      _rootRun (dart:async/zone.dart:1391:47)
#3      _CustomZone.run (dart:async/zone.dart:1301:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#8      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#9      _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#10     _StreamController.close (dart:async/stream_controller.dart:640:5)
#11     _AsyncStarStreamController.close (dart:async-patch/async_patch.dart:134:16)
<asynchronous suspension>
```

**Comment by knopp** [comment]
Are you able to read the URL (`readValue(Formats.fileUri)`) and then access the URL directly from Flutter code?

**Comment by Maksimka101** [comment]
No, I'm not

```
PathNotFoundException: Cannot open file, path = '/Users/max/Library/Group%20Containers/6N38VWS5BX.ru.keepcoder.Telegram/appstore/account-16138895038816363150/postbox/media/telegram-cloud-photo-size-2-5402088296315737174-y.jpg' (OS Error: No such file or directory, errno = 2)
```
