### ISSUE TITLE
Missing libirondash_engine_context_native.so IrondashEngineContextPlugin

### ISSUE THREAD

**Issue by nicearma** [superlistapp/super_native_extensions#296]
Hello, I'm trying to publish my application, the compilation is working fine but when i try the application from the store or locally with Test APK option I'm getting:

```
 Received exception while registering
      java.lang.reflect.InvocationTargetException
      	at java.lang.reflect.Method.invoke(Native Method)
      	at t4.a.a(Unknown Source:21)
      	at io.flutter.embedding.android.c.E(Unknown Source:9)
      	at io.flutter.embedding.android.d.q(Unknown Source:58)
      	at io.flutter.embedding.android.c.onCreate(Unknown Source:13)
      	at android.app.Activity.performCreate(Activity.java:8071)
      	at android.app.Activity.performCreate(Activity.java:8054)
      	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
      	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
      	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3680)
      	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
      	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
      	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
      	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
      	at android.os.Handler.dispatchMessage(Handler.java:106)
      	at android.os.Looper.loop(Looper.java:223)
      	at android.app.ActivityThread.main(ActivityThread.java:7945)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
      Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libirondash_engine_context_native.so" not found
      	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
      	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
      	at java.lang.System.loadLibrary(System.java:1664)
      	at dev.irondash.engine_context.IrondashEngineContextPlugin.<clinit>(Unknown Source:9)
      	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:101)
      	at java.lang.reflect.Method.invoke(Native Method) 
      	at t4.a.a(Unknown Source:21) 
      	at io.flutter.embedding.android.c.E(Unknown Source:9) 
      	at io.flutter.embedding.android.d.q(Unknown Source:58) 
      	at io.flutter.embedding.android.c.onCreate(Unknown Source:13) 
      	at android.app.Activity.performCreate(Activity.java:8071) 
      	at android.app.Activity.performCreate(Activity.java:8054) 
      	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
      	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472) 
      	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3680) 
      	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
      	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
      	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
      	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108) 
      	at android.os.Handler.dispatchMessage(Handler.java:106) 
      	at android.os.Looper.loop(Looper.java:223) 
      	at android.app.ActivityThread.main(ActivityThread.java:7945) 
      	at java.lang.reflect.Method.invoke(Native Method) 
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603) 
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
But when i tested it without the release everything seemed to be working, but when I made the app for release, the application didn't work because I'm getting that error.

My system is Windows and my Flutter version is:

```
Flutter 3.16.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ef1af02aea (11 days ago) • 2024-01-11 15:19:26 -0600
Engine • revision 4a585b7929
Tools • Dart 3.2.4 • DevTools 2.28.5
```

I would like to know if i need to add something to the build file or some kind of configuration

**Comment by knopp** [comment]
You should check the APK for jni libraries to see if the `libirondash_engine_context_native.so` library is included for all target architectures. This should be done for default, unless you have abi filters in gradle for removing the binaries (or something similar is going on).

**Comment by knopp** [comment]
For example `flutter build apk --release` for `super_clipboard_example` will have 3 architectures (arm64-v8a, armeabi-v7a, x86_64) in the lib folder, each of them containing the following files:

```
libapp.so
libflutter.so
libirondash_engine_context_native.so
libsuper_native_extensions.so
```

**Comment by nicearma** [comment]
@knopp i was using the build tools from android studio, making the flutter build commands is making all good
Probably some missing conf is added by using the Android studio tool.

Thanks for your help
