### ISSUE TITLE
[super_context_menu] error on iOS the first time the context menu is launched

### ISSUE THREAD

**Issue by JGeek00** [superlistapp/super_native_extensions#318]
When the app is started from closed, the first time you hold a list item to trigger the context menu, this error appears. That doesn't happen the next times you activate the context menu, or after a hot restart.

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3435 pos 12: '!debugNeedsPaint': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderRepaintBoundary.toImageSync (package:flutter/src/rendering/proxy_box.dart:3435:12)
#3      _getSnapshot (package:super_native_extensions/src/widget_snapshot/widget_snapshotter_internal.dart:243:26)
#4      WidgetSnapshotterStateImpl._checkSnapshots (package:super_native_extensions/src/widget_snapshot/widget_snapshotter_internal.dart:124:26)
#5      WidgetSnapshotterStateImpl._getSnapshotInner (package:super_native_extensions/src/widget_snapshot/widget_snapshotter_internal.dart:76:5)
#6      WidgetSnapshotterStateImpl.getSnapshot (package:super_native_extensions/src/widget_snapshot/widget_snapshotter_internal.dart:36:23)
#7      _ContextMenuWidgetState<…>
```

**Comment by knopp** [comment]
Can you reproduce this with the context menu example?

**Comment by knopp** [comment]
I tried the following:
```dart
   return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: ListView(            
            children: [
              ContextMenuWidget(
                menuProvider: (_) {
                  return Menu(
                    children: [
                      MenuAction(title: 'Menu Item 2', callback: () {}),
                      MenuAction(title: 'Menu Item 3', callback: () {}),
                      MenuSeparator(),
                      Menu(title: 'Submenu', children: [
                        MenuAction(title: 'Submenu Item 1', callback: () {}),
                        MenuAction(title: 'Submenu Item 2', callback: () {}),
                        Menu(title: 'Nested Submenu', children: [
                          MenuAction(title: 'Submenu Item 1', callback: () {}),
                          MenuAction(title: 'Submenu Item 2', callback: () {}),
                        ]),
                      ]),
                    ],
                  );
                },
                child: ListTile(
                  title: const Text("Webview"),
                  onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => Container(),
                    ),
                  ),
                ),
              ),
              ContextMenuWidget(
                menuProvider: (_) {
                  return Menu(
                    children: [
                      MenuAction(title: 'Menu Item 2', callback: () {}),
                      MenuAction(title: 'Menu Item 3', callback: () {}),
                      MenuSeparator(),
                      Menu(title: 'Submenu', children: [
                        MenuAction(title: 'Submenu Item 1', callback: () {}),
                        MenuAction(title: 'Submenu Item 2', callback: () {}),
                        Menu(title: 'Nested Submenu', children: [
                          MenuAction(title: 'Submenu Item 1', callback: () {}),
                          MenuAction(title: 'Submenu Item 2', callback: () {}),
                        ]),
                      ]),
                    ],
                  );
                },
                child: Material(
                  color: Theme.of(context).colorScheme.surface,
                  child: ListTile(
                    title: const Text("Splitview"),
                    onTap: () => Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Container()),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
```
With both Flutter main and stable on iPhone 11 (simulator) but was unable to reproduce this. Does it happen reliably for you?
