### ISSUE TITLE
[super_context_menu] Secondary clicking ContextMenuWidget on iPad with linked magic mouse throws errors

### ISSUE THREAD

**Issue by liplum** [superlistapp/super_native_extensions#332]
## How to reproduce
super_context_menu: 0.8.5
1. Create a simple ContextMenuWidget like the example code, and run the app on an iPad.
2. Link a magic mouse to the iPad on your MacBook.
3. Secondary click the magic mouse.
4. Bomb!

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(super_native_extensions_error, unsupported operation, unsupportedOperation, null)
#0      NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:45)
<asynchronous suspension>
#1      MenuContextImpl.showContextMenu (package:super_native_extensions/src/native/menu.dart:208)
<asynchronous suspension>
#2      DesktopContextMenuWidget._onShowContextMenu (package:super_context_menu/src/desktop.dart:249)
<asynchronous suspension>
#3      DesktopContextMenuWidget.build.<anonymous closure> (package:super_context_menu/src/desktop.dart:165)
<asynchronous suspension>
#4      _ContextMenuDetectorState._showContextMenu (package:super_context_menu/src/desktop.dart:84)
<asynchronous suspension>
```

And long press with primary click is not working with the magic mouse.
It's supposed to show the context menu aside the ContextMenuWidget without highlighting it and blurring the background.

**Comment by axplus** [comment]
same error here.
