### ISSUE TITLE
super_drag_drop not working on Android

### ISSUE THREAD

**Issue by aford22** [superlistapp/super_native_extensions#371]
I have downloaded your "example" app from this repo, ran the melos bootstrap command and then run the flutter super_drag_drop app. Thjis works great on Windows, with drag drop happening as expected. But on Android, the app runs but dragging and droppping does nothing at all. There is no response when I try to drop anything over the "Drop here" area, and the coloured "draggable" rectangles at the top are not draggable.

Have I missed something?

**Comment by knopp** [comment]
This is definitely not expected. Is there any error in the application logs?

**Comment by raj457036** [comment]
When dragging something out got this error

```
[        ] I/flutter ( 4514): PlatformException(super_native_extensions_error, invalid engine handle, engineContextError, null)
[   +6 ms] I/flutter ( 4514): #0      NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:45:7)
[        ] I/flutter ( 4514): <asynchronous suspension>
[        ] I/flutter ( 4514): #1      DragContextImpl.startDrag (package:super_native_extensions/src/native/drag.dart:241:9)
[        ] I/flutter ( 4514): <asynchronous suspension>
[        ] I/flutter ( 4514): #2      LongPressSession.extend (package:super_native_extensions/src/drag_interaction/long_press_session.dart:35:14)
[        ] I/flutter ( 4514): <asynchronous suspension>
```

When Dropping something into the app got this error

```
[+39729 ms] I/VRI[MainActivity]( 4514): Reporting drop result: false
```

**Comment by raj457036** [comment]
Any news?

**Comment by TheArchitect123** [comment]
I'm also getting the same issue @knopp

**Comment by TheArchitect123** [comment]
E/flutter (11953): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(super_native_extensions_error, invalid engine handle, engineContextError, null)
E/flutter (11953): #0      NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:45:7)
E/flutter (11953): <asynchronous suspension>
E/flutter (11953): #1      DragContextImpl.startDrag (package:super_native_extensions/src/native/drag.dart:241:9)
E/flutter (11953): <asynchronous suspension>
E/flutter (11953): #2      LongPressSession.extend (package:super_native_extensions/src/drag_interaction/long_press_session.dart:35:14)       
E/flutter (11953): <asynchronous suspension>
E/flutter (11953):

**Comment by TheArchitect123** [comment]
I got this error ever since upgrading to the latest Flutter SDK (v3.24.3).
I also can't rollback anymore to a previous version, because it will cause issues on my current project.

**Comment by raj457036** [comment]
just checking in! any update on this?

**Comment by ganwumeng** [comment]
If you are using FlutterFragmentActivity, but not FlutterActivity, then you will meet this problem. (At least for me)

Under this circumstance, just change the code in IrondashEngineContextPlugin.java.

Original:
```java
  static public View getFlutterView(long handle) {
    final Activity activity = getActivity(handle);
    if (activity != null) {
      return activity.findViewById(FlutterActivity.FLUTTER_VIEW_ID);
    } else {
      return null;
    }
  }
```

After:
```java
  private static FlutterView findFlutterViewRecursive(View view) {
    if (view instanceof FlutterView) {
      return (FlutterView) view;
    }
    
    if (view instanceof ViewGroup) {
      ViewGroup viewGroup = (ViewGroup) view;
      for (int i = 0; i < viewGroup.getChildCount(); i++) {
        View child = viewGroup.getChildAt(i);
        FlutterView result = findFlutterViewRecursive(child);
        if (result != null) {
          return result;
        }
      }
    }
    
    return null;
  }

  static public View getFlutterView(long handle) {
    final Activity activity = getActivity(handle);
    if (activity == null) {
      return null;
    }
    
    View flutterView = activity.findViewById(FlutterActivity.FLUTTER_VIEW_ID);
    if (flutterView != null) {
      return flutterView;
    }
    
    View decorView = activity.getWindow().getDecorView();
    return findFlutterViewRecursive(decorView.getRootView());
  }
```

**Comment by Tutorialwork** [comment]
I managed it to get the plugin running with the ``FlutterFragmentActivity`` by using this customized ``MainActivity.kt`` file.

```java
class MainActivity: FlutterFragmentActivity() {

    override fun onPostResume() {
        super.onPostResume()

        val view = findViewById<View>(android.R.id.content) as? ViewGroup
        if (view != null) {
            val flutterView = findFlutterView(view)
            if (flutterView != null) {
                flutterView.id = FlutterActivity.FLUTTER_VIEW_ID
            }
        }
    }

    private fun findFlutterView(view: ViewGroup): FlutterView? {
        for (i in 0 until view.childCount) {
            val child = view.getChildAt(i)
            if (child is FlutterView) {
                return child
            } else if (child is ViewGroup) {
                val result = findFlutterView(child)
                if (result != null) return result
            }
        }
        return null
    }
}
```
