### ISSUE TITLE
[super_clipboard] Impossible to copy to clipboard on iOS using static linkage

### ISSUE THREAD

**Issue by bloemy7** [superlistapp/super_native_extensions#406]
Hi,

I saw in a couple of spots that `super_native_extensions` is made for dynamic linking, but unfortunately constraints on our projects are such that we need to do static linkage.

I followed the steps here: https://github.com/superlistapp/super_native_extensions/issues/136

which enabled me to properly build. This works on web & Android without issues, as well as when building locally to my iPhone device.

But in release or in Testflight, copying fails:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'super_native_extensions_init_message_channel_context': dlsym(RTLD_DEFAULT, super_native_extensions_init_message_channel_context): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
#1      _getNativeContext (package:super_native_extensions/src/native/context.dart:14)
#2      _nativeContext (package:super_native_extensions/src/native/context.dart:20)
#3      ClipboardReader.instance (package:super_native_extensions/src/clipboard_reader.dart)
#4      SystemClipboard.instance (package:super_clipboard/src/system_clipboard.dart)
```

Is there any workaround for this or not?

Thank you.

**Comment by knopp** [comment]
The way our cocoapods integration works (cargokit) can not be done to support static linking unfortunately. So there is no workaround for this. Eventually it will be migrated to Dart/Flutter native assets (once no longer experimental) and this will not be na issue anymore.

**Comment by bloemy7** [comment]
Ok, thanks for the explanation. Is there a timeline currently for the porting to native Dart or not?
