### ISSUE TITLE
The following NoSuchChannelException was thrown running a test: Native MessageChannel "DragManager" not found

### ISSUE THREAD

**Issue by nelsoncampos-cloudwalk** [superlistapp/super_native_extensions#410]
Widgets with super_context_menu are throwing this error in the widget testing
someone already went through this? Start to happening when I updated the flutter version.

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following NoSuchChannelException was thrown running a test:
Native MessageChannel "DragManager" not found

When the exception was thrown, this was the stack:
#0      MockMessageChannelContext._sendMessage (package:irondash_message_channel/src/mock_message_channel_context.dart:47:7)
#1      MockMessageChannelContext.registerChannel.<anonymous closure> (package:irondash_message_channel/src/mock_message_channel_context.dart:41:37)
#2      MessageChannel.sendMessage (package:irondash_message_channel/src/message_channel.dart:36:26)
#3      NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:41:39)
#4      DragContextImpl.initialize (package:super_native_extensions/src/native/drag.dart:98:20)
<asynchronous suspension>
#5      DragContext.instance.<anonymous closure> (package:super_native_extensions/src/drag.dart:142:9)
<asynchronous suspension>
#6      Mutex.protect (package:super_native_extensions/src/mutex.dart:15:13)
<asynchronous suspension>
#7      LongPressHandler.create (package:super_native_extensions/src/drag_interaction/long_press_handler.dart:33:20)
<asynchronous suspension>
#8      _initializeIfNeeded (package:super_context_menu/src/menu_internal.dart:168:24)
<asynchronous suspension>


```

**Comment by tdenniston** [comment]
Seeing the same issue with super_drag_and_drop 0.9.1

```
The following NoSuchChannelException was thrown running a test (but after the test had completed):
Native MessageChannel "DropManager" not found

When the exception was thrown, this was the stack:
#0      MockMessageChannelContext._sendMessage (package:irondash_message_channel/src/mock_message_channel_context.dart:47:7)
#1      MockMessageChannelContext.registerChannel.<anonymous closure> (package:irondash_message_channel/src/mock_message_channel_context.dart:41:37)
#2      MessageChannel.sendMessage (package:irondash_message_channel/src/message_channel.dart:36:26)
#3      NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:41:39)
#4      DropContextImpl.registerDropFormats (package:super_native_extensions/src/native/drop.dart:200:21)
#5      DropFormatRegistry._updateIfNeeded (package:super_drag_and_drop/src/drop_internal.dart:348:15)
<asynchronous suspension>
```
