### ISSUE TITLE
Unable to resolve arm64-v8a/libsuper_native_extensions.so (MO0BSF - SHARED LIBRARY BINARY ANALYSIS Reports).

### ISSUE THREAD

**Issue by santhoshkumar4035** [superlistapp/super_native_extensions#448]
After Testing my Application in MOBSF it throws some Warnings so how to resolve SHARED LIBRARY BINARY ANALYSIS warnings.
i've attached full testing report:

![image](https://github.com/user-attachments/assets/96bdd4c5-b5c3-4701-91fe-e8e1a928013d)

[reports.pdf](https://github.com/user-attachments/files/17254346/reports.pdf)

**Comment by knopp** [comment]
The stack protection can probably be enabled through a rustc flag. Symbol stripping can be done at later stage so it's not really relevant (I don't think we should strip symbols by default) and I'm not sure how much fortified functions are relevant for Rust. I don't think that the code in `super_native_extensions` calls any unsafe glibc functions directly.

**Comment by TheWash7** [comment]
I added the flutter module to Android and used **super_clipboard: ^0.8.24**. The following error occurred when entering flutter:
```
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@8bceb5f) but could not find or invoke the GeneratedPluginRegistrant.
Received exception while registering
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1343)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:220)
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:645)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8929)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
**Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libirondash_engine_context_native.so" not found**
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at dev.irondash.engine_context.IrondashEngineContextPlugin.<clinit>(IrondashEngineContextPlugin.java:153)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:39)
	at java.lang.reflect.Method.invoke(Native Method) 
	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80) 
	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1343) 
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:220) 
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:645) 
	at android.app.Activity.performCreate(Activity.java:8960) 
	at android.app.Activity.performCreate(Activity.java:8929) 
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456) 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:230) 
	at android.os.Looper.loop(Looper.java:319) 
	at android.app.ActivityThread.main(ActivityThread.java:8913) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
```

After I removed **super_clipboard: ^0.8.24** in the flutter module, the program ran normally. Why does this problem occur? In addition, I set `abiFilters.addAll(listOf("armeabi-v7a", "arm64-v8a", "x86", "x86_64"))` in build.gradle.kts.

**Comment by TheWash7** [comment]
There are some strange errors when the program starts, but these garbled characters make me have no idea where to start. Can you please take a look at this problem and give me some ideas?
![Image](https://github.com/user-attachments/assets/fcdb6796-2f2e-4690-b937-dd5472f826f0)

**Comment by kevin4hig** [comment]
any solution?
