### ISSUE TITLE
Unable to launch on Android. Got java.lang.RuntimeException: Unable to get provider com.superlist.super_native_extensions.DataProvider: java.lang.ClassNotFoundException: Didn't find class "com.superlist.super_native_extensions.DataProvider" on path

### ISSUE THREAD

**Issue by x-ji** [superlistapp/super_native_extensions#478]
Hi, I wonder if I didn't configure something correctly. I can launch my app on MacOS and iOS without any issue, but when I try to launch it on Android, I get the following error:

I followed the instructions listed under the "Android support" section in the README. I also tried to rebuild the project after `flutter clean` to no avail.

Appreciate your help here 🙏 .

```
Launching lib/main.dart on VER N49 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
W/FlutterAnimationAdvance(18904): FlutterAnimationAdvance getInstance()
E/AndroidRuntime(18904): FATAL EXCEPTION: main
E/AndroidRuntime(18904): Process: com.example.pomo_gtd, PID: 18904
E/AndroidRuntime(18904): java.lang.RuntimeException: Unable to get provider com.superlist.super_native_extensions.DataProvider: java.lang.ClassNotFoundException: Didn't find class "com.superlist.super_native_extensions.DataProvider" on path: DexPathList[[zip file "/data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/base.apk"],nativeLibraryDirectories=[/data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/lib/arm64, /data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/base.apk!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
E/AndroidRuntime(18904): 	at android.app.ActivityThread.installProvider(ActivityThread.java:9153)
E/AndroidRuntime(18904): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8648)
E/AndroidRuntime(18904): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8296)
E/AndroidRuntime(18904): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(18904): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2858)
E/AndroidRuntime(18904): 	at android.os.Handler.dispatchMessage(Handler.java:117)
E/AndroidRuntime(18904): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(18904): 	at android.os.Looper.loop(Looper.java:302)
E/AndroidRuntime(18904): 	at android.app.ActivityThread.main(ActivityThread.java:9652)
E/AndroidRuntime(18904): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18904): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
E/AndroidRuntime(18904): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
E/AndroidRuntime(18904): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.superlist.super_native_extensions.DataProvider" on path: DexPathList[[zip file "/data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/base.apk"],nativeLibraryDirectories=[/data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/lib/arm64, /data/app/~~WcJH9-JA68nRoALdX6J_9Q==/com.example.pomo_gtd-oRmCNNmS0kV7pY8rHd536A==/base.apk!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
E/AndroidRuntime(18904): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(18904): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
E/AndroidRuntime(18904): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
E/AndroidRuntime(18904): 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
E/AndroidRuntime(18904): 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:66)
E/AndroidRuntime(18904): 	at android.app.ActivityThread.installProvider(ActivityThread.java:9137)
E/AndroidRuntime(18904): 	... 11 more
Application finished.

Exited.
```

**Comment by x-ji** [comment]
When I remove the content provider declaration from `app/src/main/AndroidManifest.xml` the app launches. I'm probably doing something wrong here 🤔 :

```
        <provider
        android:name="com.superlist.super_native_extensions.DataProvider"
            android:authorities="com.example.pomo_gtd.SuperClipboardDataProvider"
            android:exported="true"
            android:grantUriPermissions="true" >
        </provider>
```

**Comment by x-ji** [comment]
OK I think what happened might be that I upgraded `flutter_quill` to the latest version, and it turns out it doesn't have `super_clipboard` as a dependency anymore. Thus I simply needed to remove this part from the manifest 😅 .
